#FROM python:3.11-slim

#WORKDIR /app

#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

version: "3.8"

services:
  app:
    container_name: devsecops-day1-demo
    build:
      context: .
      dockerfile: Dockerfile
    image: devsecops-day1-demo:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
   

